version: "2"

services:
  jupyter:
    image: osminafrica:latest
    container_name: jupyter-geonotebook
    ports:
      - "8888:8888"
    volumes:
      - ./notebook:/home/jovyan/notebook
      - ./data:/home/jovyan/data
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: "start-notebook.sh --NotebookApp.custom_display_url=http://localhost:8888"
    mem_limit: 10gb