name: osm-in-africa
channels:
  - conda-forge
dependencies:
  - python=3.7.*
  - pip
  - notebook=5.7.8
  - jupyterhub=1.0.0
  - jupyterlab=0.35.5
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - fiona
  - geopandas
  - shapely
  - beautifulsoup4
  - cartopy
  - geojson
  - pyproj
  - ipywidgets
  - dask
  - pip:
    - osmium